# Generated by Django 3.2.4 on 2021-06-30 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_article_article_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_image',
            field=models.ImageField(default='./static/images/default.jgg', upload_to='articles/'),
        ),
    ]
